<#
.SYNOPSIS
  Builds the release binaries for one architecture and the NSIS installer around them.

.DESCRIPTION
  Output: dist\MKLM-Setup-<version>-<arch>.exe, plus dist\SHA256SUMS for every installer in dist.
  The version comes from [workspace.package] in Cargo.toml. Unsigned for now: code signing, when
  it comes, signs the three exes before makensis and the installer after it (see SIGNING below).

.EXAMPLE
  .\installer\build-installer.ps1 -Arch x64
  .\installer\build-installer.ps1 -Arch arm64
#>
[CmdletBinding()]
param(
    [ValidateSet('x64', 'arm64')] [string]$Arch = 'x64',
    [string]$Makensis,
    [switch]$SkipBuild
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$target = @{ x64 = 'x86_64-pc-windows-msvc'; arm64 = 'aarch64-pc-windows-msvc' }[$Arch]

$cargoToml = Get-Content -Raw (Join-Path $root 'Cargo.toml')
if ($cargoToml -notmatch '(?ms)^\[workspace\.package\].*?^version\s*=\s*"([^"]+)"') {
    throw 'No version in [workspace.package] of Cargo.toml.'
}
$version = $Matches[1]
# VIProductVersion needs four numbers: drop any pre-release or build suffix, append .0.
$viVersion = ($version -replace '[-+].*$', '') + '.0'

if (-not $Makensis) {
    $candidates = @(
        (Get-Command makensis.exe -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source),
        (Join-Path ${env:ProgramFiles(x86)} 'NSIS\makensis.exe'),
        (Join-Path $env:ProgramFiles 'NSIS\makensis.exe')
    ) | Where-Object { $_ -and (Test-Path $_) }
    $Makensis = $candidates | Select-Object -First 1
}
if (-not $Makensis) { throw 'makensis.exe not found (install NSIS 3.12 or later, or pass -Makensis).' }
$nsisVersion = (& $Makensis -VERSION).Trim()
if ([version]($nsisVersion.TrimStart('v') -replace '[^0-9.].*$', '') -lt [version]'3.11') {
    throw "NSIS $nsisVersion is too old: 3.11 or later is required (CVE-2025-43715)."
}

if (-not $SkipBuild) {
    & cargo build --release --locked --target $target -p mklm -p mklm-cli -p mklm-helper
    if ($LASTEXITCODE -ne 0) { throw "cargo build failed ($LASTEXITCODE)." }
}
$src = Join-Path $root "target\$target\release"
foreach ($exe in 'mklm.exe', 'mklm-cli.exe', 'mklm-helper.exe') {
    if (-not (Test-Path (Join-Path $src $exe))) { throw "$exe is missing in $src." }
}

# The GUI's icon is generated by its build script into OUT_DIR; use the newest one.
$icon = Get-ChildItem (Join-Path $root "target\$target\release\build") -Filter mklm.ico -Recurse -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1

# SIGNING: sign mklm.exe, mklm-cli.exe and mklm-helper.exe here (before they are packed), and the
# installer after makensis. Not done yet: MKLM is unsigned for now (plan 5).

$dist = Join-Path $root 'dist'
New-Item -ItemType Directory -Force $dist | Out-Null
$outFile = Join-Path $dist "MKLM-Setup-$version-$Arch.exe"
$defines = @(
    "/DVERSION=$version", "/DVIVERSION=$viVersion", "/DARCH=$Arch",
    "/DSRCDIR=$src", "/DROOT=$root", "/DOUTFILE=$outFile"
)
if ($icon) { $defines += "/DICON=$($icon.FullName)" }
& $Makensis /V2 /INPUTCHARSET UTF8 @defines (Join-Path $PSScriptRoot 'nsis\mklm.nsi')
if ($LASTEXITCODE -ne 0) { throw "makensis failed ($LASTEXITCODE)." }

$sums = Get-ChildItem $dist -Filter 'MKLM-Setup-*.exe' | Sort-Object Name | ForEach-Object {
    '{0}  {1}' -f (Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant(), $_.Name
}
[System.IO.File]::WriteAllLines((Join-Path $dist 'SHA256SUMS'), [string[]]$sums)
Write-Host "Built $outFile ($([math]::Round((Get-Item $outFile).Length / 1MB, 1)) MB) with NSIS $nsisVersion"
